Import('env')

env.InstallFrontend(['contact.html', 'help.html', 'layout.html',
                     'submit.html', 'download.html', 'index.html',
                     'results_ok.html', 'results_failed.html'], 'templates')
