include ../Makefile.include
DISTFILES=bg_3.gif logo33-space.gif modloop_title_blue.gif logo33.gif \
          pdfsml.gif index.html help.html modloop.css


install:
	mkdir -p ${HTML}
	cp ${DISTFILES} ${HTML}
